apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pl-volume
  labels:
    type: local
spec:
  storageClassName: mannual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: mannual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
