apiVersion: v1
kind: Service
metadata:
  name: drupal-offical
spec:
  selector:
    app: drupal-offical
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  drupal-offical
  namespace: default
  labels:
    app:  drupal-offical
spec:
  selector:
    matchLabels:
      app: drupal-offical
  replicas: 1
  template:
    metadata:
      labels:
        app:  drupal-offical
    spec:
      containers:
      - name:  drupal
        image:  drupal
        resources:
          requests:
            cpu: 1000m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /robots.txt
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  80
          name:  drupal-offical
      restartPolicy: Always
