apiVersion: v1
kind: Pod
metadata:
  name:  busybox-hostpath
  namespace: default
  labels:
    app:  busybox-hostpath
spec:
  containers:
  - name:  busybox
    image:  busybox
    command:
      - "sleep"
      - "36000"
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - name: busybox-hostpath-dir
      mountPath: /data/dir 
    - name: busybox-hostpath-file
      mountPath: /data/file
  volumes:
    - name: busybox-hostpath-dir
      hostPath:
        path: /data/busybox-hostpath-dir
        type: DirectoryOrCreate
    - name: busybox-hostpath-file
      hostPath:
        path: /data/busybox-hostpath-file
        type: FileOrCreate