apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rewrite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: default
spec:
  rules:
  - host: k8s-drupal.com
    http:
      paths:
      - path: /vol(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: drupal-vol-service
            port: 
              number: 80
  ingressClassName: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-vol-service
spec:
  selector:
    app: drupal-vol 
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32008
---
apiVersion: v1
kind: Pod
metadata:
  name:  drupal-vol
  namespace: default
  labels:
    app:  drupal-vol
spec:
  containers:
  - name:  drupal-vol1
    image:  zterry95/drupal-quick
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - name: drupal-sqlite
      mountPath: /data
  volumes:
    - name: drupal-sqlite
      persistentVolumeClaim:
        claimName: drupal-quick-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-quick-sqlite
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/drupal-quick-sqlite"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-quick-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
